let types = {
  // Profitability
  GET_PROFITABILITY_REQUEST: 'GET_PROFITABILITY_REQUEST',
  GET_PROFITABILITY_REQUEST_SUCCESS: 'GET_PROFITABILITY_REQUEST_SUCCESS',
  GET_PROFITABILITY_REQUEST_FAIL: 'GET_PROFITABILITY_REQUEST_FAIL',

  //Cost to mine
  GET_COSTTOMINE_REQUEST: 'GET_COSTTOMINE_REQUEST',
  GET_COSTTOMINE_REQUEST_SUCCESS: 'GET_COSTTOMINE_REQUEST_SUCCESS',
  GET_COSTTOMINE_REQUEST_FAIL: 'GET_COSTTOMINE_REQUEST_FAIL',

  //Difficulty Stats
  GET_DIFFICULTYSTATS_REQUEST: 'GET_DIFFICULTYSTATS_REQUEST',
  GET_DIFFICULTYSTATS_REQUEST_SUCCESS: 'GET_DIFFICULTYSTATS_REQUEST_SUCCESS',

  //Hash Rate Stats
  GET_HASHRATESTATS_REQUEST: 'GET_HASHRATESTATS_REQUEST',
  GET_HASHRATESTATS_REQUEST_SUCCESS: 'GET_HASHRATESTATS_REQUEST_SUCCESS',
  GET_HASHRATESTATS_REQUEST_FAIL: 'GET_HASHRATESTATS_REQUEST_FAIL'

};
export default types;
  